# Generated by Django 3.0.14 on 2022-03-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodePostal',
            fields=[
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False)),
            ],
        ),
    ]
